version: '3.8'
services: 
  frontend:
    container_name: frontend
    image: nginx:latest
    ports:
      - "8081:80"
    depends_on:
      - backend
      - php
      - imageserver
    volumes:
      - ./frontend/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynet
    restart: always

  php:
    container_name: php-fpm
    image: php:fpm
    networks:
      - mynet
    volumes:
      - ./frontend/:/var/www/html
    restart: always

  imageserver:
    container_name: imageserver
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./images/:/usr/share/nginx/html
    networks:
      - mynet
    restart: always

  backend:  
    container_name: backend
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: bash -c "npm install express cors mysql2 & npx nodemon index.js "
    working_dir: /app
    networks:
      - mynet
    restart: always

  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "SeveN062"
      MYSQL_DATABASE: "mydatabase"
    volumes:
      - ./database/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynet
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306 
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - mynet
    volumes:
      - ./htpasswd:/etc/nginx/.htpasswd
    restart: always

networks:
  mynet:
    external: true
volumes:
  mysql_data:
