version: '3.8'
services: 
  frontend:
    container_name: frontend
    image: nginx:latest
    ports:
      - "8081:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/:/usr/share/nginx/html
    networks:
      - mynet
  backend:  
    container_name: backend
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: bash -c "npm load & npm start"
    working_dir: /app
    networks:
      - mynet
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "SeveNO62"
      MYSQL_DATABASE: "mydatabase"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynet

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - mynet
    volumes:
      - ./htpasswd:/etc/nginx/.htpasswd
networks:
  mynet:
    external: true
volumes:
  mysql_data:
